### PR TITLE
[Fix] Session Block

### LINKED ISSUE #160: Session Block Padding
On Android the lists have zero padding/margins and therefore the items all run together, making it hard to see relevant information at a glance.

Screenshot

### PR DESCRIPTION
**Pull request by hopeman15**
This fixes the padding issues on the session blocks. When you have a time slot with multiple sessions they all ran together. This fixes #160 

| Before | After |
| ------------- | ------------- |
| Screenshot_before | Screenshot_after |

### CODE REVIEW

**Comment by hopeman15** [comment]
Hey everyone, what's the status on getting this one in before NYC 🇺🇸 or the London 🇬🇧 droidcon 🙌

**Comment by hopeman15** [comment]
😢

**Comment by TadeasKriz** [comment]
Hey @hopeman15, we've had a lot going on. Thank you for the PR, unfortunately our goal was to put the sessions that begin at the same time into a single block. The implementation on Android isn't great as it indeed looks broken. Instead it should look like a single card with the content divided by separators.

**Comment by hopeman15** [comment]
@TadeasKriz I see 🤔 new PR in coming 🎁

**Pull request closed without merging**
