### PR TITLE
Adding date update script

### PR DESCRIPTION
**Pull request by KevinSchildhorn**

### CODE REVIEW

**Comment by kpgalligan** [comment]
Can we make this more flexible? Pass in the source file as a path arg on the command line and print out to console/stdout? We'll be able to direct output to wherever with a bash script. In theory you could also read from stdin, but that won't buy much.

I'd also like to be able to pass in the first date instead of "today". We'll need to test past, current, and future dates.

**Comment by KevinSchildhorn** [comment]
Sure, I'll add some arguments to the script like source path and starting date.

**Comment by KevinSchildhorn** [comment]
So you would prefer bash over python? The reason I was picking python was because it's simpler to parse JSON files with python (and I couldn't get jq to install)

**Comment by kpgalligan** [comment]
Python is fine, but we can write bash scripts to call that. I would definitely **not** try to write this in bash entirely

**Comment by KevinSchildhorn** [comment]
I've added arguments for path, name, and date. Also I added a -h argument for help

usage: updateDates.py [option] ... [-fp | -fn | -d] [arg] ...
-fp   : FilePath, defaults to "sessionize/app/src/main/assets/"
-fn   : FilePath, defaults to "schedule.json"
-d    : Date, defaults to todays date

**Comment by KevinSchildhorn** [comment]
Removed file name option

**Comment by kpgalligan** [comment]
Let's call this good for now and review adding time as a possible enhancement later.

**Pull request merged**
